name: Deploy Django Project to Koyeb

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Collect static files
      run: python manage.py collectstatic --noinput
    - name: Install Koyeb CLI
      run: |
        curl -fsSL https://cli.koyeb.com/install.sh | sh
    - name: Deploy to Koyeb
      env:
        KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
      run: |
        koyeb app init simplepbpshop
        koyeb service init simplepbpshop-service \
          --git github.com/${{ github.repository }} \
          --git-branch master \
          --ports 8000:http \
          --routes /:8000 \
          --env PORT=8000 \
          --env DJANGO_SETTINGS_MODULE=simplepbpshop.settings \
          --env DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
          --env DEBUG=False
        koyeb app deploy simplepbpshop